var routes = [
    { start: "JURONG EAST", end: "JURONG WEST" },
    { start: "JURONG EAST", end: "CLEMENTI" },
    { start: "JURONG WEST", end: "BUKIT BATOK" },
    { start: "BUKIT BATOK", end: "BUKIT PANJANG" },
    { start: "BUKIT BATOK", end: "CHOA CHU KANG" },
    { start: "CHOA CHU KANG", end: "SUNGEI KADUT" },
    { start: "BUKIT PANJANG", end: "SUNGEI KADUT" },
    { start: "CLEMENTI", end: "BUKIT TIMAH" },
    { start: "CLEMENTI", end: "BUKIT BATOK" },
    { start: "CLEMENTI", end: "QUEENSTOWN" },
    { start: "BUKIT TIMAH", end: "BUKIT PANJANG" },
    { start: "QUEENSTOWN", end: "BUKIT MERAH" },
    { start: "QUEENSTOWN", end: "KALLANG" },
    { start: "BUKIT TIMAH", end: "CLEMENTI" },
    { start: "BUKIT TIMAH", end: "CLEMENTI" },
    { start: "BUKIT TIMAH", end: "TOA PAYOH" },
    { start: "BUKIT TIMAH", end: "BISHAN" },
    { start: "SUNGEI KADUT", end: "WOODLANDS" },
    { start: "SUNGEI KADUT", end: "WOODLANDS" },
    { start: "KALLANG", end: "TOA PAYOH" },
    { start: "KALLANG", end: "GEYLANG" },
    { start: "KALLANG", end: "MARINE PARADE" },
    { start: "KALLANG", end: "HOUGANG" },
    { start: "TOA PAYOH", end: "BISHAN" },
    { start: "TOA PAYOH", end: "ANG MO KIO" },
    { start: "ANG MO KIO", end: "YISHUN" },
    { start: "ANG MO KIO", end: "SERANGOON" },
    { start: "ANG MO KIO", end: "BISHAN" },
    { start: "WOODLANDS", end: "SEMBAWANG" },
    { start: "SEMBAWANG", end: "YISHUN" },
    { start: "SERANGOON", end: "HOUGANG" },
    { start: "SERANGOON", end: "SENGKANG" },
    { start: "GEYLANG", end: "BEDOK" },
    { start: "GEYLANG", end: "HOUGANG" },
    { start: "HOUGANG", end: "SENGKANG" },
    { start: "SENGKANG", end: "PUNGGOL" },
    { start: "PUNGGOL", end: "PASIR RIS" },
    { start: "PASIR RIS", end: "TAMPINES" },
    { start: "BEDOK", end: "TAMPINES" },


];

console.log(Number(null));